$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath 'C:\Users\IP\Documents\Codex\2026-09-25\i-w\work\x-to-youtube-automation'
$env:X_COOKIES_JSON = Get-Content -Raw 'C:\Tools\TwitterTelegramMyPalestine1\twitter_cookies.json'
$env:DOWNLOAD_DIR = 'H:\My Drive\Rafa\Unused'
$env:TIMEZONE = 'Africa/Cairo'
python main.py *> 'C:\Users\IP\Documents\Codex\2026-09-25\i-w\work\x-to-youtube-automation\local-checker.log'
$env:DOWNLOAD_DIR = 'H:\My Drive\Rafa\Unused'
$env:DOWNLOAD_MANIFEST = 'H:\My Drive\Rafa\.automation\downloaded_videos.json'
python tiktok_monitor.py --accounts-file 'C:\Users\IP\Documents\Codex\2026-09-25\i-w\work\x-to-youtube-automation\tiktok_accounts.txt' --count 10 *> 'C:\Users\IP\Documents\Codex\2026-09-25\i-w\work\x-to-youtube-automation\tiktok-checker.log'
